#!/bin/sh
CC=${CC:-cc}

$CC src/kite-meta/kite-meta.c src/kite.c src/sout.c -Isrc/ -o kite-meta
$CC src/rawtokite/rawtokite.c src/kite.c src/sout.c -Isrc/ -o rawtokite
$CC src/kite-info/kite-info.c src/kite.c src/sout.c -Isrc/ -o kite-info
$CC src/kitetoraw/kitetoraw.c src/kite.c src/sout.c -Isrc/ -o kitetoraw
